# opt-in to Travis new infrastructure
sudo: false

# cache stuff, hopefully shortening build times
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers

jdk: oraclejdk8
language: scala
scala:
  - 2.11.12
  - 2.12.4

matrix:
  include:
  - scala: 2.13.0-M4
    script:
    - sbt "++${TRAVIS_SCALA_VERSION}!" test:compile # TODO

script:
  - sbt ++$TRAVIS_SCALA_VERSION test
